name: ssh command

on:
  push:
    branches:
      - develop


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          public-key: ${{ secrets.DEV_SSH_KEY }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: bash /app/deploy_test.sh aoi_kobayashi