name: ssh command

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_SSHE_SSH_KEY }}" > ~/.ssh/id_ed25519  # GitHub Actionsが使用する秘密鍵のファイル名
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t rsa ${{ secrets.DEV_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and deploy
        uses: invi5H/ssh-action@v1
        with:
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}

          - name: Deploy using rsync
         run: |
            mkdir -p /usr/share/nginx/html/aoi_kobayashi
            rsync -r --delete-after /c/env/qa-marathon07/ /usr/share/nginx/html/aoi_kobayashi
